#!/bin/bash
git update-index --assume-unchanged src/common-libs/openssl-1.0.2h/Makefile
git update-index --assume-unchanged src/common-libs/openssl-1.0.2h/Makefile.bak
git update-index --assume-unchanged src/common-libs/openssl-1.0.2h/apps/CA.pl
git update-index --assume-unchanged src/common-libs/openssl-1.0.2h/crypto/opensslconf.h
git update-index --assume-unchanged src/common-libs/openssl-1.0.2h/tools/c_rehash
git update-index --assume-unchanged src/common-libs/pcre-8.38/INSTALL
git update-index --assume-unchanged src/common-libs/pcre-8.38/Makefile.in
git update-index --assume-unchanged src/common-libs/pcre-8.38/aclocal.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/ar-lib
git update-index --assume-unchanged src/common-libs/pcre-8.38/compile
git update-index --assume-unchanged src/common-libs/pcre-8.38/config.guess
git update-index --assume-unchanged src/common-libs/pcre-8.38/config.h.in
git update-index --assume-unchanged src/common-libs/pcre-8.38/config.sub
git update-index --assume-unchanged src/common-libs/pcre-8.38/configure
git update-index --assume-unchanged src/common-libs/pcre-8.38/depcomp
git update-index --assume-unchanged src/common-libs/pcre-8.38/install-sh
git update-index --assume-unchanged src/common-libs/pcre-8.38/ltmain.sh
git update-index --assume-unchanged src/common-libs/pcre-8.38/m4/libtool.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/m4/ltoptions.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/m4/ltsugar.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/m4/ltversion.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/m4/lt~obsolete.m4
git update-index --assume-unchanged src/common-libs/pcre-8.38/missing
git update-index --assume-unchanged src/common-libs/pcre-8.38/test-driver
git update-index --assume-unchanged src/common-libs/zlib-1.2.8/Makefile
git update-index --assume-unchanged src/common-libs/zlib-1.2.8/zconf.h
